### ISSUE TITLE
hardcoded output_bucket to "loudml" ?

### ISSUE THREAD

**Issue by toni-moreno** [vsergeyev/loudml-grafana-app#15]
Hello @vsergeyev I'm sorry. I can not see outgoing data, and 

I've configured output bucket as "XXXXXX_loudml" , but it seems like sending "loudml" when created the model.

![image](https://user-images.githubusercontent.com/5883405/88573046-6c333100-d040-11ea-869d-b60b7aa85cd4.png)

Could be perhaps a bug  in the plugin, or something I did wrong ?

I've recreated the model twice and again output_bucket = loudml instead of "XXXXXX_loudml"

![image](https://user-images.githubusercontent.com/5883405/88574989-7a368100-d043-11ea-8061-83bdca1ed956.png)

**Comment by vsergeyev** [comment]
Hello @toni-moreno 

It is a bug. Going to commit fix soon.

Thank you for detailed debug info 👍 

V.

**Comment by vsergeyev** [comment]
@toni-moreno 

Please test fix in grafana/6.x branch, or use this packge for docker:

```
docker run -d \
  -p 3000:3000 \
  --name=grafana \
  -e "GF_INSTALL_PLUGINS=https://github.com/vsergeyev/loudml-grafana-app/raw/master/loudml-grafana-app-1.6.0.zip;loudml-grafana-app" \
  grafana/grafana
```

**Comment by toni-moreno** [comment]
Hello @vsergeyev thank you very much for this fast fix !!
