### ISSUE TITLE
Config not available

### ISSUE THREAD

**Issue by darox** [vsergeyev/loudml-grafana-app#8]
I am having a weird issue, there's no config available in the plugin settings. I am doing something wrong?
![image](https://user-images.githubusercontent.com/9934402/83864742-76623e80-a725-11ea-9b43-96b730e0fb82.png)
Thank you

**Comment by vsergeyev** [comment]
Hello @darox 

Config is on a page of Loud ML Datasource.
So you should create one.
Datasource has URL of Loud ML server to be configured.

Thank you for your feedback on this,
this is likely a UX gap. Let me think on how to improve this.

V.

**Comment by darox** [comment]
@vsergeyev Thank you for replying so quickly. My bad definitely....

I was able to add the data source and model. 
![image](https://user-images.githubusercontent.com/9934402/83967323-a0039d00-a8c0-11ea-9b7d-00eb9d78eff9.png)

How can I start the training?

**Comment by vsergeyev** [comment]
Hello @darox 

This functionality wasn't implemented in full scale. My bad.

Started to work on it. Right now implemented saving (added save button in dialog) for new and existing models.

V.

**Comment by vsergeyev** [comment]
@darox have recorded this tutorial video https://youtu.be/Fm_7HThLGdo

**Comment by darox** [comment]
Great, I'll have  a look.

**Comment by darox** [comment]
I gave it another try, but now not even a single config options is visible:
![image](https://user-images.githubusercontent.com/9934402/88797057-01e6d180-d1a3-11ea-98b2-81fba28b5b9c.png)

**Comment by vsergeyev** [comment]
@darox thank you for spending time and testing it,
really appreciate!

It is a bug I'm dealing with on Grafana 7.x.

They have upgraded a way for plugins to show config options.
So it is actually an update exercise.

-Volodymyr

**Comment by darox** [comment]
Let me know if I can support with testing. Honestly I'm struggling with the official documentation of LoudML. I miss so much information..
